module.exports = (api, controller, middleware) => {
    api.get(
        '/user/form/viewAssessment',
        middleware.checkPermission.canRead,
        controller.form.viewForm
    );
    api.post(
        '/user/form/createAssessment',
        middleware.checkRole.isAdminOrHr,
        controller.form.createForm
    );
    api.put(
        '/user/form/updateAssessment',
        middleware.checkPermission.canUpdate,
        middleware.validateData.validateForm,
        controller.form.updateForm
    );
    api.post(
        '/user/form/submitAssessment',
        middleware.checkPermission.canWrite,
        middleware.validateData.validateForm,
        controller.form.submitForm
    );
    api.put(
        '/user/form/approveAssessment',
        middleware.checkPermission.canApprove,
        middleware.checkFormExpiration,
        controller.form.approveForm
    );
    api.put(
        '/user/form/closeAssessment',
        middleware.checkRole.isAdminOrHr,
        middleware.checkFormExpiration,
        controller.form.closeForm);

    api.get(
        '/user/form/viewProbationary',
        middleware.checkPermission.canRead,
        controller.form.viewForm
    );
    api.post(
        '/user/form/createProbationary',
        middleware.checkRole.isAdminOrHr,
        controller.form.createForm
    );
    api.put(
        '/user/form/updateProbationary',
        middleware.checkPermission.canUpdate,
        controller.form.updateForm
    );
    api.post(
        '/user/form/submitProbationary',
        middleware.checkPermission.canWrite,
        middleware.validateData.validateForm,
        controller.form.submitForm
    );
    api.put(
        '/user/form/approveProbationary',
        middleware.checkPermission.canApprove,
        middleware.checkFormExpiration,
        controller.form.approveForm
    );
    api.put(
        '/user/form/closeProbationary',
        middleware.checkRole.isAdminOrHr,
        middleware.checkFormExpiration,
        controller.form.closeForm
    );

}